[package]
name = "bundleq"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
access-json = "0.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
sonic-rs = "0.5"
jmespath = { version = "0.3", features = ["sync"] }
zstd = "0.13"
anyhow = "1.0"
serde_json = "1"
indicatif = "0.17"
rayon = "1.10"
simd-json = "0.13"
libc = "0.2"